services:
  db:
    image: postgres:15
    container_name: odoo18_db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo18_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 10

  odoo:
    build: .
    image: odoo18_app
    container_name: odoo18_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -d odoo -i base
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo

volumes:
  odoo18_db_data:
